add TwoSum solution
TECHOUS/codemash pull request #107
Opened 2024-10-06 09:31 UTC by Shubham0523

2024-10-07 10:25 UTC, GauravWalia19 requested changes

2024-10-07 10:25 UTC, GauravWalia19 commented on CodeBase/TwoSum.js
> +}
Please call this method `twoSum` and add a `console.log` for printing the result so that we can run the code and verify also.

2024-10-07 10:26 UTC, GauravWalia19 commented on CodeBase/TwoSum.js
> +}
And please do support us by giving staring this repository

2024-10-07 16:40 UTC, Shubham0523 commented
done @GauravWalia19 please review the request now

2024-10-08 13:56 UTC, GauravWalia19 approved these changes
Changes looks good

2024-10-08 13:57 UTC, merged